#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/asus/picasso

PRODUCT_COPY_FILES += \
    vendor/asus/picasso/proprietary/system_ext/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/dpm/dpm.conf \
    vendor/asus/picasso/proprietary/system_ext/etc/init/dpmd.rc:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/init/dpmd.rc \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/com.android.hotwordenrollment.common.util.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.android.hotwordenrollment.common.util.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/com.qti.location.sdk.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qti.location.sdk.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/com.qualcomm.location.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.location.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/com.qualcomm.qti.izattools.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/com.qualcomm.qti.izattools.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/dpmapi.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/izat.xt.srv.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/izat.xt.srv.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/privapp-permissions-com.qualcomm.location.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/privapp-permissions-com.qualcomm.location.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/qcrilhook.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qcrilhook.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/qti_libpermissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_libpermissions.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/qti_permissions.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/qti_permissions.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephony_system-ext_privapp-permissions-qti.xml \
    vendor/asus/picasso/proprietary/system_ext/etc/permissions/telephonyservice.xml:$(TARGET_COPY_OUT_SYSTEM_EXT)/etc/permissions/telephonyservice.xml \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/Picasso/Picasso_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Picasso/Picasso_Bluetooth_cal.acdb \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/Picasso/Picasso_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Picasso/Picasso_General_cal.acdb \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/Picasso/Picasso_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Picasso/Picasso_Global_cal.acdb \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/Picasso/Picasso_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Picasso/Picasso_Handset_cal.acdb \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/Picasso/Picasso_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Picasso/Picasso_Hdmi_cal.acdb \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/Picasso/Picasso_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Picasso/Picasso_Headset_cal.acdb \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/Picasso/Picasso_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Picasso/Picasso_Speaker_cal.acdb \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/Picasso/Picasso_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/Picasso/Picasso_workspaceFile.qwsp \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.0.0_0.1__3.0.0_0.0__eai_1.10.pmd \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.00.pmd \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.3.0_0.1__3.0.0_0.0__eai_1.10.pmd \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_ns_models/fai__2.7.20_0.0__3.0.0_0.0__eai_1.10.pmd \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai_3.0.0_0.0_eai_1.00.pmd \
    vendor/asus/picasso/proprietary/vendor/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.10.pmd:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/nn_vad_models/fai__3.0.0_0.0__eai_1.10.pmd \
    vendor/asus/picasso/proprietary/vendor/etc/apdr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/apdr.conf \
    vendor/asus/picasso/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/asus/picasso/proprietary/vendor/etc/camera/eisoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/eisoverridesettings.txt \
    vendor/asus/picasso/proprietary/vendor/etc/charger_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fstab.qti \
    vendor/asus/picasso/proprietary/vendor/etc/charger_fw_fstab.qti:$(TARGET_COPY_OUT_VENDOR)/etc/charger_fw_fstab.qti \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile1.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile2.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile3.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile4.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile5.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ATT/ATT_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ATT/ATT_profile6.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile1.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile15.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile15.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile16.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile16.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile17.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile18.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile19.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile19.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile2.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile20.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile21.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile21.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile3.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile32.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile32.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile4.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile5.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile6.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/ROW/ROW_profile7.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/ROW/ROW_profile7.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile1.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile2.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile3.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile3.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile4.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile4.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile5.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile5.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cne/wqeclient/VZW/VZW_profile6.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cne/wqeclient/VZW/VZW_profile6.xml \
    vendor/asus/picasso/proprietary/vendor/etc/configstore/vpp.configstore.xml:$(TARGET_COPY_OUT_VENDOR)/etc/configstore/vpp.configstore.xml \
    vendor/asus/picasso/proprietary/vendor/etc/cvp/v2.0/facedetection/model1.dat:$(TARGET_COPY_OUT_VENDOR)/etc/cvp/v2.0/facedetection/model1.dat \
    vendor/asus/picasso/proprietary/vendor/etc/cvp/v2.1/facedetection/model2.dat:$(TARGET_COPY_OUT_VENDOR)/etc/cvp/v2.1/facedetection/model2.dat \
    vendor/asus/picasso/proprietary/vendor/etc/data/dsi_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/dsi_config.xml \
    vendor/asus/picasso/proprietary/vendor/etc/data/netmgr_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/data/netmgr_config.xml \
    vendor/asus/picasso/proprietary/vendor/etc/default-permissions/com.qualcomm.qti.cne.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default-permissions/com.qualcomm.qti.cne.xml \
    vendor/asus/picasso/proprietary/vendor/etc/display/DPU660.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU660.xml \
    vendor/asus/picasso/proprietary/vendor/etc/display/DPU670.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU670.xml \
    vendor/asus/picasso/proprietary/vendor/etc/display/DPU7__.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/DPU7__.xml \
    vendor/asus/picasso/proprietary/vendor/etc/display/advanced_sf_offsets.xml:$(TARGET_COPY_OUT_VENDOR)/etc/display/advanced_sf_offsets.xml \
    vendor/asus/picasso/proprietary/vendor/etc/flp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/flp.conf \
    vendor/asus/picasso/proprietary/vendor/etc/gpfspath_oem_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gpfspath_oem_config.xml \
    vendor/asus/picasso/proprietary/vendor/etc/gps.conf:$(TARGET_COPY_OUT_VENDOR)/etc/gps.conf \
    vendor/asus/picasso/proprietary/vendor/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.biometrics.fingerprint@2.1-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/android.hardware.bluetooth@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.bluetooth@1.0-service-qti.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/android.hardware.drm@1.3-service.widevine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.drm@1.3-service.widevine.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/android.hardware.gnss@2.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gnss@2.1-service-qti.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/android.hardware.keymaster@4.1-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@4.1-service-qti.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.neuralnetworks@1.3-service-qti.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/cnd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/cnd.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/dataadpl.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataadpl.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/dataqti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dataqti.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/dpmQmiMgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dpmQmiMgr.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/hw/init.qti.kernel.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.qti.kernel.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/ims_rtp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ims_rtp_daemon.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/imsdaemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/imsdaemon.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/init-qcril-data.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init-qcril-data.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/init.qti.media.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.media.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/init.qti.qcv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.qti.qcv.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/init.time_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.time_daemon.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/init.vendor.sensors.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.vendor.sensors.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/init_qfp_daemon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_qfp_daemon.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/init_thermal-engine.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init_thermal-engine.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/ipa_fws.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipa_fws.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/ipacm-diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipacm-diag.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/irisdbgd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/irisdbgd.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/mutualex.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mutualex.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/netmgrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netmgrd.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/port-bridge.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/port-bridge.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/qconfig.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qconfig.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/qcrilNrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qcrilNrd.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/qdcmss.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qdcmss.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/qmipriod.debug.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.debug.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/qmipriod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qmipriod.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/qseecomd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/qseecomd.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/shsusrd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/shsusrd.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/ssgtzd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ssgtzd.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.display.color@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.display.color@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.pixelworks.hardware.display.iris-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.pixelworks.hardware.display.iris-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.pixelworks.hardware.feature.irisfeature-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.pixelworks.hardware.feature.irisfeature-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.adsprpc-guestos-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.adsprpc-guestos-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.cdsprpc-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.cdsprpc-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.diag.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.diag.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.esepowermanager@1.1-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.esepowermanager@1.1-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.hardware.alarm@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.alarm@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.capabilityconfigstore@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.hardware.charger_monitor@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.charger_monitor@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.hardware.dsp@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.dsp@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.hardware.eid@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.eid@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.hardware.factory@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.factory@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qseecom@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.qteeconnector@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.hardware.soter@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.soter@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.hardware.tui_comm@1.0-service-qti.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.media.c2@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.media.c2@1.0-service.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.rmt_storage.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.rmt_storage.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.qti.tftp.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.qti.tftp.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.sensors.qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.qti.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vendor.sensors.sscrpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.sensors.sscrpcd.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vmmgr.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vmmgr.rc \
    vendor/asus/picasso/proprietary/vendor/etc/init/vppservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vppservice.rc \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm1.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm1.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm20.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm20.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm21.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm21.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm22.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm22.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm23.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm23.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm30.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm30.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm31.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm31.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm32.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm32.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm33.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm33.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm4.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm4.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm5.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm5.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inParm6.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inParm6.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/VersioControl.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/VersioControl.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm1.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm1.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm2.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm2.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm20.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm20.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm21.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm21.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm22.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm22.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm23.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm23.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm3.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm3.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm30.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm30.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm31.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm31.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm32.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm32.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm33.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm33.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm4.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm4.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm5.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm5.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/inparm_anakin_pr/inParm6.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/inparm_anakin_pr/inParm6.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/mcf.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/mcf.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/iris6/pxlw_iris6.mcf:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/iris6/pxlw_iris6.mcf \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm1.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm1.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm10.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm10.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm11.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm11.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm12.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm12.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm13.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm13.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm14.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm14.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm15.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm15.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm16.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm16.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm17.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm17.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm18.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm18.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm2.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm2.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm3.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm3.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm4.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm4.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm5.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm5.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm6.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm6.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm7.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm7.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm8.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm8.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inParm9.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inParm9.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/ModifyHistory.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/ModifyHistory.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm1.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm1.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm10.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm10.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm11.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm11.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm12.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm12.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm13.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm13.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm14.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm14.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm15.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm15.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm16.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm16.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm17.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm17.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm18.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm18.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm2.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm2.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm3.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm3.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm4.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm4.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm5.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm5.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm6.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm6.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm7.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm7.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm8.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm8.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/inParm9.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/inParm9.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_anakin_pr/mcfCheck.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_anakin_pr/mcfCheck.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/Release.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/Release.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm1.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm1.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm10.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm10.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm11.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm11.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm12.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm12.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm13.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm13.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm14.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm14.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm15.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm15.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm16.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm16.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm17.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm17.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm18.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm18.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm2.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm2.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm3.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm3.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm4.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm4.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm5.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm5.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm6.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm6.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm7.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm7.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm8.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm8.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_sake_pr/inParm9.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_sake_pr/inParm9.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/Release.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/Release.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm1.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm1.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm10.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm10.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm11.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm11.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm12.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm12.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm13.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm13.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm14.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm14.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm15.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm15.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm16.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm16.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm17.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm17.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm18.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm18.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm2.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm2.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm3.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm3.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm4.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm4.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm5.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm5.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm6.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm6.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm7.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm7.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm8.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm8.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/inparm_vodka_pr/inParm9.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/inparm_vodka_pr/inParm9.txt \
    vendor/asus/picasso/proprietary/vendor/etc/inparm/irissoft/mcfCheck.txt:$(TARGET_COPY_OUT_VENDOR)/etc/inparm/irissoft/mcfCheck.txt \
    vendor/asus/picasso/proprietary/vendor/etc/irissoft.fw:$(TARGET_COPY_OUT_VENDOR)/etc/irissoft.fw \
    vendor/asus/picasso/proprietary/vendor/etc/irissoft_a.fw:$(TARGET_COPY_OUT_VENDOR)/etc/irissoft_a.fw \
    vendor/asus/picasso/proprietary/vendor/etc/irissoft_s.fw:$(TARGET_COPY_OUT_VENDOR)/etc/irissoft_s.fw \
    vendor/asus/picasso/proprietary/vendor/etc/irissoft_v.fw:$(TARGET_COPY_OUT_VENDOR)/etc/irissoft_v.fw \
    vendor/asus/picasso/proprietary/vendor/etc/izat.conf:$(TARGET_COPY_OUT_VENDOR)/etc/izat.conf \
    vendor/asus/picasso/proprietary/vendor/etc/lowi.conf:$(TARGET_COPY_OUT_VENDOR)/etc/lowi.conf \
    vendor/asus/picasso/proprietary/vendor/etc/media/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media/video_system_specs.json \
    vendor/asus/picasso/proprietary/vendor/etc/media_lahaina/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/media_lahaina/video_system_specs.json \
    vendor/asus/picasso/proprietary/vendor/etc/media_profiles.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles.xml \
    vendor/asus/picasso/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/asus/picasso/proprietary/vendor/etc/media_profiles_lahaina.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_lahaina.xml \
    vendor/asus/picasso/proprietary/vendor/etc/media_profiles_vendor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_vendor.xml \
    vendor/asus/picasso/proprietary/vendor/etc/permissions/android.hardware.light.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.light.xml \
    vendor/asus/picasso/proprietary/vendor/etc/permissions/android.hardware.telephony.gsm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.telephony.gsm.xml \
    vendor/asus/picasso/proprietary/vendor/etc/permissions/android.hardware.telephony.ims.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.telephony.ims.xml \
    vendor/asus/picasso/proprietary/vendor/etc/permissions/qti_fingerprint_interface.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/qti_fingerprint_interface.xml \
    vendor/asus/picasso/proprietary/vendor/etc/permissions/vendor.qti.hardware.factory.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/vendor.qti.hardware.factory.xml \
    vendor/asus/picasso/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/qcrilNr.db:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/qcrilNr.db \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/upgrade/config/config/6.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/config/6.0_config.sql \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/upgrade/config/config/7.0_config.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/config/config/7.0_config.sql \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/upgrade/other/0_initial_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/0_initial_qcrilnr.sql \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/upgrade/other/1_version_intro_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/1_version_intro_qcrilnr.sql \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/upgrade/other/2_version_add_wps_config_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/2_version_add_wps_config_qcrilnr.sql \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/upgrade/other/3_version_update_wps_config_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/3_version_update_wps_config_qcrilnr.sql \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/upgrade/other/4_version_update_ecc_table_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/4_version_update_ecc_table_qcrilnr.sql \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/upgrade/other/5_version_update_ecc_table_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/5_version_update_ecc_table_qcrilnr.sql \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/upgrade/other/6_version_change_property_table_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/6_version_change_property_table_qcrilnr.sql \
    vendor/asus/picasso/proprietary/vendor/etc/qcril_database/upgrade/other/7_version_update_ecc_table_qcrilnr.sql:$(TARGET_COPY_OUT_VENDOR)/etc/qcril_database/upgrade/other/7_version_update_ecc_table_qcrilnr.sql \
    vendor/asus/picasso/proprietary/vendor/etc/qfp_config.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qfp_config.txt \
    vendor/asus/picasso/proprietary/vendor/etc/qfp_config_dbg.txt:$(TARGET_COPY_OUT_VENDOR)/etc/qfp_config_dbg.txt \
    vendor/asus/picasso/proprietary/vendor/etc/sap.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sap.conf \
    vendor/asus/picasso/proprietary/vendor/etc/sec_config:$(TARGET_COPY_OUT_VENDOR)/etc/sec_config \
    vendor/asus/picasso/proprietary/vendor/etc/seccomp_policy/codec2.vendor.ext-arm.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/codec2.vendor.ext-arm.policy \
    vendor/asus/picasso/proprietary/vendor/etc/seccomp_policy/imsrtp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/imsrtp.policy \
    vendor/asus/picasso/proprietary/vendor/etc/seccomp_policy/qcrilnr@2.0.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qcrilnr@2.0.policy \
    vendor/asus/picasso/proprietary/vendor/etc/seccomp_policy/qti-systemd.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/qti-systemd.policy \
    vendor/asus/picasso/proprietary/vendor/etc/seccomp_policy/vendor.qti.hardware.dsp.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/vendor.qti.hardware.dsp.policy \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/af6133e_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/af6133e_0.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/cedros_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/cedros_default_sensors.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/cedros_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/cedros_dynamic_sensors.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/cedros_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/cedros_irq.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/cedros_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/cedros_power_0.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/icm4x6xx_0.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/lahaina_af6133e_R5D_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lahaina_af6133e_R5D_0.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/lahaina_af6133e_R5ER1_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lahaina_af6133e_R5ER1_0.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/lahaina_af6133e_R5ER2_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lahaina_af6133e_R5ER2_0.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/lahaina_af6133e_R5PR_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lahaina_af6133e_R5PR_0.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/lahaina_default_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lahaina_default_sensors.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/lahaina_dynamic_sensors.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lahaina_dynamic_sensors.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/lahaina_icm4x6xx_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lahaina_icm4x6xx_0.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/lahaina_irq.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lahaina_irq.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/lahaina_power_0.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/lahaina_power_0.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_amd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_amd_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_disabled.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_amd_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_amd_sw_enabled.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_aont.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_aont.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_basic_gestures.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_basic_gestures.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_bring_to_ear.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_bring_to_ear.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_ccd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_ccd_v2_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v2_walk.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_ccd_v3_1_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_1_walk.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_ccd_v3_walk.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_ccd_v3_walk.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_cm.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_cm.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_dae.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dae.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_device_orient.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_device_orient.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_diag_filter.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_diag_filter.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_distance_bound.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_distance_bound.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_dpc.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_dpc.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_facing.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_facing.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_fmv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_fmv_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_fmv_legacy.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_geomag_rv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_geomag_rv.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_gyro_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_gyro_cal.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_heart_rate.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_heart_rate.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_mag_cal.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_mag_cal_legacy.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_mag_cal_legacy.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_multishake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_multishake.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_pedometer.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_pedometer.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_rmd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rmd.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_rotv.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_rotv.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_smd.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_smd.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_tilt.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_tilt_sw_disabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_disabled.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_tilt_sw_enabled.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_sw_enabled.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_tilt_to_wake.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_tilt_to_wake.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/config/sns_wrist_pedo.json:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/config/sns_wrist_pedo.json \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/sensors_list.txt:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensors_list.txt \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/sensors_settings:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensors_settings \
    vendor/asus/picasso/proprietary/vendor/etc/sensors/sns_reg_config:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sns_reg_config \
    vendor/asus/picasso/proprietary/vendor/etc/snapdragon_color_libs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/snapdragon_color_libs_config.xml \
    vendor/asus/picasso/proprietary/vendor/etc/ssg/ta_config.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/ta_config.json \
    vendor/asus/picasso/proprietary/vendor/etc/ssg/tz_whitelist.json:$(TARGET_COPY_OUT_VENDOR)/etc/ssg/tz_whitelist.json \
    vendor/asus/picasso/proprietary/vendor/etc/templates/20x30/dfan/dfan1.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/20x30/dfan/dfan1.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/20x30/dfan/dfan2.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/20x30/dfan/dfan2.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/20x30/dfan/dfan3.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/20x30/dfan/dfan3.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/20x30/dfan/dfan4.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/20x30/dfan/dfan4.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/20x30/dfan/dfan5.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/20x30/dfan/dfan5.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/20x30/slant/slant1.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/20x30/slant/slant1.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/20x30/slant/slant2.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/20x30/slant/slant2.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/4x9/dfan/dfan1.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/4x9/dfan/dfan1.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/4x9/dfan/dfan2.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/4x9/dfan/dfan2.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/4x9/dfan/dfan3.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/4x9/dfan/dfan3.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/4x9/dfan/dfan4.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/4x9/dfan/dfan4.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/4x9/slant/slant1.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/4x9/slant/slant1.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/4x9/slant/slant2.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/4x9/slant/slant2.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/4x9/slant/slant3.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/4x9/slant/slant3.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/4x9/slant/slant4.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/4x9/slant/slant4.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/8x8/dfan/dfan1.PGM:$(TARGET_COPY_OUT_VENDOR)/etc/templates/8x8/dfan/dfan1.PGM \
    vendor/asus/picasso/proprietary/vendor/etc/templates/8x8/dfan/dfan2.PGM:$(TARGET_COPY_OUT_VENDOR)/etc/templates/8x8/dfan/dfan2.PGM \
    vendor/asus/picasso/proprietary/vendor/etc/templates/8x8/dfan/dfan3.PGM:$(TARGET_COPY_OUT_VENDOR)/etc/templates/8x8/dfan/dfan3.PGM \
    vendor/asus/picasso/proprietary/vendor/etc/templates/8x8/dfan/dfan4.PGM:$(TARGET_COPY_OUT_VENDOR)/etc/templates/8x8/dfan/dfan4.PGM \
    vendor/asus/picasso/proprietary/vendor/etc/templates/8x8/slant/slant1.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/8x8/slant/slant1.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/8x8/slant/slant2.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/8x8/slant/slant2.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/8x8/slant/slant3.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/8x8/slant/slant3.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/templates/8x8/slant/slant4.pgm:$(TARGET_COPY_OUT_VENDOR)/etc/templates/8x8/slant/slant4.pgm \
    vendor/asus/picasso/proprietary/vendor/etc/thermal-engine.conf:$(TARGET_COPY_OUT_VENDOR)/etc/thermal-engine.conf \
    vendor/asus/picasso/proprietary/vendor/etc/video_system_specs.json:$(TARGET_COPY_OUT_VENDOR)/etc/video_system_specs.json \
    vendor/asus/picasso/proprietary/vendor/etc/vmmgr.conf:$(TARGET_COPY_OUT_VENDOR)/etc/vmmgr.conf \
    vendor/asus/picasso/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/asus/picasso/proprietary/vendor/etc/wifi/vendor_cmd.xml:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/vendor_cmd.xml \
    vendor/asus/picasso/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/asus/picasso/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/asus/picasso/proprietary/vendor/firmware/Data.msc:$(TARGET_COPY_OUT_VENDOR)/firmware/Data.msc \
    vendor/asus/picasso/proprietary/vendor/firmware/a660_gmu.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_gmu.bin \
    vendor/asus/picasso/proprietary/vendor/firmware/a660_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_sqe.fw \
    vendor/asus/picasso/proprietary/vendor/firmware/a660_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_zap.b00 \
    vendor/asus/picasso/proprietary/vendor/firmware/a660_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_zap.b01 \
    vendor/asus/picasso/proprietary/vendor/firmware/a660_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_zap.b02 \
    vendor/asus/picasso/proprietary/vendor/firmware/a660_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_zap.elf \
    vendor/asus/picasso/proprietary/vendor/firmware/a660_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a660_zap.mdt \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b00 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b01 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b02 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b03 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b04 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b05 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b06 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b07 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b08 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b09 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b10 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b11 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b12 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b13 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b14 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b15 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b16 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b17 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b18 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b19 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b20 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b21:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b21 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b22:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b22 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b23:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b23 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b24:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b24 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b25:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b25 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.b26:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.b26 \
    vendor/asus/picasso/proprietary/vendor/firmware/adsp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/adsp.mdt \
    vendor/asus/picasso/proprietary/vendor/firmware/amss.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/amss.bin \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b00 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b01 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b02 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b03 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b04 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b05 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b06 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b07 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b08 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b09 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b10 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b11 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b12 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b13 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b14 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b15 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.b16 \
    vendor/asus/picasso/proprietary/vendor/firmware/cdsp.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/cdsp.mdt \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b04 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b05 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b06 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b07 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b10 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b11 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b12 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b13 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b14 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b15 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b16 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b17 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b18 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/asus/picasso/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/asus/picasso/proprietary/vendor/firmware/fingerpr.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b00 \
    vendor/asus/picasso/proprietary/vendor/firmware/fingerpr.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b01 \
    vendor/asus/picasso/proprietary/vendor/firmware/fingerpr.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b02 \
    vendor/asus/picasso/proprietary/vendor/firmware/fingerpr.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b03 \
    vendor/asus/picasso/proprietary/vendor/firmware/fingerpr.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b04 \
    vendor/asus/picasso/proprietary/vendor/firmware/fingerpr.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b05 \
    vendor/asus/picasso/proprietary/vendor/firmware/fingerpr.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b06 \
    vendor/asus/picasso/proprietary/vendor/firmware/fingerpr.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.b07 \
    vendor/asus/picasso/proprietary/vendor/firmware/fingerpr.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/fingerpr.mdt \
    vendor/asus/picasso/proprietary/vendor/firmware/hdcpsrm.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/hdcpsrm.b00 \
    vendor/asus/picasso/proprietary/vendor/firmware/hdcpsrm.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/hdcpsrm.b01 \
    vendor/asus/picasso/proprietary/vendor/firmware/hdcpsrm.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/hdcpsrm.b02 \
    vendor/asus/picasso/proprietary/vendor/firmware/hdcpsrm.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/hdcpsrm.b03 \
    vendor/asus/picasso/proprietary/vendor/firmware/hdcpsrm.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/hdcpsrm.b04 \
    vendor/asus/picasso/proprietary/vendor/firmware/hdcpsrm.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/hdcpsrm.b05 \
    vendor/asus/picasso/proprietary/vendor/firmware/hdcpsrm.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/hdcpsrm.b06 \
    vendor/asus/picasso/proprietary/vendor/firmware/hdcpsrm.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/hdcpsrm.b07 \
    vendor/asus/picasso/proprietary/vendor/firmware/hdcpsrm.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/hdcpsrm.mbn \
    vendor/asus/picasso/proprietary/vendor/firmware/hdcpsrm.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/hdcpsrm.mdt \
    vendor/asus/picasso/proprietary/vendor/firmware/ipa_fws.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b00 \
    vendor/asus/picasso/proprietary/vendor/firmware/ipa_fws.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b01 \
    vendor/asus/picasso/proprietary/vendor/firmware/ipa_fws.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b02 \
    vendor/asus/picasso/proprietary/vendor/firmware/ipa_fws.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b03 \
    vendor/asus/picasso/proprietary/vendor/firmware/ipa_fws.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.b04 \
    vendor/asus/picasso/proprietary/vendor/firmware/ipa_fws.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.elf \
    vendor/asus/picasso/proprietary/vendor/firmware/ipa_fws.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/ipa_fws.mdt \
    vendor/asus/picasso/proprietary/vendor/firmware/iris6.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/iris6.fw \
    vendor/asus/picasso/proprietary/vendor/firmware/iris6_ccf1.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/iris6_ccf1.fw \
    vendor/asus/picasso/proprietary/vendor/firmware/iris6_ccf2.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/iris6_ccf2.fw \
    vendor/asus/picasso/proprietary/vendor/firmware/iris6_ccf3.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/iris6_ccf3.fw \
    vendor/asus/picasso/proprietary/vendor/firmware/m3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/m3.bin \
    vendor/asus/picasso/proprietary/vendor/firmware/regdb.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/regdb.bin \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b00 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b01 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b02 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b03 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b04 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b05 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b06 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b07 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b08 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b09 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b10 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b11 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b12 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b13 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b14 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b15 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b16 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b17 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b18 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b19 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b20 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b21:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b21 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b22:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b22 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b23:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b23 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.b24:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.b24 \
    vendor/asus/picasso/proprietary/vendor/firmware/slpi.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/slpi.mdt \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b00 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b01 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b02 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b03 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b04 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b05 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b06 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b07 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b08 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b09 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b10 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b11 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b12 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b13 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b14 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b15 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b16 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b17 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b18 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.b19 \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.mbn \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.mdt \
    vendor/asus/picasso/proprietary/vendor/firmware/vpu20_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v_unsigned.mbn \
    vendor/asus/picasso/proprietary/vendor/firmware/wlan/qca_cld/WCNSS_qcom_cfg.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/wlan/qca_cld/WCNSS_qcom_cfg.ini \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/Almalence/Asus_Picasso_tele.cfg:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/Almalence/Asus_Picasso_tele.cfg \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/Almalence/Asus_Picasso_tele_Single_Frame.cfg:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/Almalence/Asus_Picasso_tele_Single_Frame.cfg \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/Almalence/Asus_Picasso_ultra_wide.cfg:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/Almalence/Asus_Picasso_ultra_wide.cfg \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/Almalence/Asus_Picasso_ultra_wide_Single_Frame.cfg:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/Almalence/Asus_Picasso_ultra_wide_Single_Frame.cfg \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/Almalence/Asus_Picasso_wide_bin.cfg:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/Almalence/Asus_Picasso_wide_bin.cfg \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/Almalence/Asus_Picasso_wide_bin_Single_Frame.cfg:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/Almalence/Asus_Picasso_wide_bin_Single_Frame.cfg \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/Almalence/Asus_Picasso_wide_remosaic.cfg:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/Almalence/Asus_Picasso_wide_remosaic.cfg \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/Almalence/Asus_Picasso_wide_remosaic_Single_Frame.cfg:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/Almalence/Asus_Picasso_wide_remosaic_Single_Frame.cfg \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/arch/DIT_List.cfg:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/arch/DIT_List.cfg \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/ditSCidGen/msgchk.db:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/ditSCidGen/msgchk.db \
    vendor/asus/picasso/proprietary/vendor/lib64/DataSet/ispDB/ParameterDB.db:$(TARGET_COPY_OUT_VENDOR)/lib64/DataSet/ispDB/ParameterDB.db \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/arcsoft_dc_calibration_t.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/arcsoft_dc_calibration_t.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/arcsoft_dc_calibration_u.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/arcsoft_dc_calibration_u.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/arcsoft_dc_calibration_w.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/arcsoft_dc_calibration_w.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/arcsoft_eis_configure:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/arcsoft_eis_configure \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/com.qti.sensormodule.imx686_16m_p.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.imx686_16m_p.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/com.qti.sensormodule.imx686_p.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.imx686_p.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/com.qti.sensormodule.liteon_imx363_p.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.liteon_imx363_p.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/com.qti.sensormodule.ov08a10_p.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.ov08a10_p.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/com.qti.sensormodule.ov24b1q_p.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.sensormodule.ov24b1q_p.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/com.qti.tuned.imx363.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.imx363.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/com.qti.tuned.imx686.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.imx686.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/com.qti.tuned.ov08a.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.ov08a.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/com.qti.tuned.ov24b1q.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.ov24b1q.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/dut_IMX363_P.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/dut_IMX363_P.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/dut_IMX686_P.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/dut_IMX686_P.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/dut_OV08A10_P.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/dut_OV08A10_P.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/dut_OV24B1Q_P.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/dut_OV24B1Q_P.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/template_0.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/template_0.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/template_1.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/template_1.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/template_2.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/template_2.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/template_6.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/template_6.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/camera/template_7.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/template_7.bin \
    vendor/asus/picasso/proprietary/vendor/lib64/style.cng:$(TARGET_COPY_OUT_VENDOR)/lib64/style.cng \
    vendor/asus/picasso/proprietary/vendor_dlkm/lib/modules/modules.blocklist:$(TARGET_COPY_OUT_VENDOR_DLKM)/lib/modules/modules.blocklist

PRODUCT_PACKAGES += \
    btaudio_offload_if \
    com.qti.eeprom.truly_cmb433 \
    com.qti.sensor.imx363_p \
    com.qti.sensor.imx686_16m_p \
    com.qti.sensor.imx686_p \
    com.qti.sensor.ov08a10_p \
    com.qti.sensor.ov24b1q_p \
    com.qti.sensor.ov8856 \
    com.arc.node.eisv2 \
    com.arc.node.eisv3 \
    com.arcsoft.node.autozoom \
    com.arcsoft.node.smooth_transition \
    com.qti.camx.chiiqutils \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.Almalence \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.dewarp \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gpu \
    com.qti.node.memcpy \
    com.qti.node.mffusion \
    com.qti.node.ml \
    com.qti.node.remosaic \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swmfnr \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.autoroi \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    com.qti.chiusecaseselector \
    com.qti.feature2.generic \
    com.qti.stats.common \
    com.qualcomm.qti.dpm.api@1.0_vendor \
    com.qualcomm.qti.imscmservice@1.0 \
    com.qualcomm.qti.imscmservice@2.0 \
    com.qualcomm.qti.imscmservice@2.1 \
    com.qualcomm.qti.imscmservice@2.2 \
    eglSubDriverAndroid \
    libEGL_adreno \
    libGLESv1_CM_adreno \
    libGLESv2_adreno \
    libq3dtools_adreno \
    libq3dtools_esx \
    android.hardware.bluetooth@1.0-impl-qti \
    audio.primary.lahaina \
    camera.qcom \
    com.dsi.ant@1.0-impl \
    com.qti.chi.override \
    vendor.qti.hardware.bluetooth_audio@2.0-impl \
    vendor.qti.hardware.bluetooth_sar@1.1-impl \
    vendor.qti.hardware.btconfigstore@1.0-impl \
    vendor.qti.hardware.btconfigstore@2.0-impl \
    vendor.qti.hardware.capabilityconfigstore@1.0-impl \
    vulkan.adreno \
    libAlacSwDec \
    libApeSwDec \
    libC2D2 \
    libCB \
    libFlacSwDec \
    libMpeghSwEnc \
    libOpenCL \
    libSuperSensor \
    libSuperSensorCPU \
    libSuperSensorProcessor \
    libSuperSensorProcessorCWrapper \
    libVkLayer_q3dtools \
    libacdb-fts \
    libacdbloader \
    libacdbrtac \
    libadiertac \
    libadreno_utils \
    libadsprpc \
    libaidenoiser \
    libarcsoft_bokehplus_video \
    libarcsoft_eis_wrapper \
    libarcsoft_low_light_shot \
    libarcsoft_multicamautozoom \
    libarcsoft_triple_sat \
    libarcsoft_triple_zoomtranslator \
    libaudcal \
    libaudio_log_utils \
    libaudioalsa \
    libaudioconfigstore \
    libaudioparsers \
    libbatching \
    libbitmlengine \
    libbluetooth_audio_session_qti \
    libbt-hidlclient \
    libbtnv \
    libc2d30_bltlib \
    libcamera_nn_stub \
    libcamerapostproc \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libcapiv2svacnn \
    libcapiv2svarnn \
    libcapiv2vop \
    libcdsprpc \
    libchiarcutils \
    libchilog \
    libcne \
    libcneapiclient \
    libcneoplookup \
    libcneqmiutils \
    libcom.qti.chinodeutils \
    libconfigdb \
    libcvp2_1 \
    libcvp_common \
    libdiag \
    libdpmqmihal \
    libdsi_netctrl \
    libdsutils \
    libfastcvdsp_stub \
    libfastcvopt \
    libgcs-calwrapper \
    libgcs-ipc \
    libgcs-osal \
    libgcs \
    libgps.utils \
    libgpudataproducer \
    libgsl \
    libhdmipassthru \
    libidl \
    libipebpsstriping \
    libjpege \
    liblistensoundmodel2 \
    libllvm-glnext \
    libllvm-qcom \
    libloc_core \
    liblqe \
    libmdmdetect \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmmosal_vendor \
    libmpbase \
    libmulawdec \
    libnetmgr \
    libnetmgr_common \
    libnetmgr_nr_fusion \
    libnetmgr_rmnet_ext \
    libofflinedump \
    libofflinelog \
    libopencv \
    libopencv3a \
    libopestriping \
    liboptical_zoom_dc \
    liboptical_zoom_vs \
    libos \
    libpdmapper \
    libpdnotifier \
    libperipheral_client \
    libpowercore \
    libqc2colorconvertfilter \
    libqc2filter \
    libqc2vppfilter \
    libqcci_legacy \
    libqcodec2_base \
    libqcodec2_basecodec \
    libqcodec2_core \
    libqcodec2_hooks \
    libqcodec2_mockfilter \
    libqcodec2_platform \
    libqcodec2_utils \
    libqcodec2_v4l2codec \
    libqconfigclient \
    libqcrilNr \
    libqcrilNrFramework \
    libqcrilNrLogger \
    libqcrilNrQtiBus \
    libqcrilNrQtiMutex \
    libqcrildatactl \
    libqdi \
    libqdp \
    libqfp-service \
    libqll10 \
    libqllengine \
    libqmi \
    libqmi_cci \
    libqmi_client_helper \
    libqmi_client_qmux \
    libqmi_common_so \
    libqmi_csi \
    libqmi_csvt_srvc \
    libqmi_encdec \
    libqmi_legacy \
    libqmiservices \
    libqrtr \
    libqsocket \
    libqtigef \
    libril-db \
    libril-qc-ltedirectdisc \
    libril-qc-radioconfig \
    libril-qcril-hook-oem \
    librilqmimiscservices \
    librilqmiservices \
    libscveCommon \
    libscveCommon_stub \
    libscveObjectSegmentation \
    libscveObjectSegmentation_stub \
    libscveObjectTracker \
    libscveObjectTracker_stub \
    libsensor_hal_l5 \
    libsensorslog \
    libsmemlog \
    libsnsapi \
    libstagefright_soft_qtiflacdec \
    libswregistrationalgo \
    libsynx \
    libsystem_health_mon \
    libtfestriping \
    libthermalclient \
    libthreadutils \
    libtime_genoff \
    libtriplecam_optical_zoom_control \
    libtriplecam_video_optical_zoom \
    libvideooptfeature \
    libxditk_arch \
    libxditk_ditArchLIB \
    libxditk_ditBSP \
    libxml \
    qcrilMarshal \
    qcrild_libqcrilnrutils \
    qtiril-utils \
    qtiwakelock \
    sensors.hal.tof \
    libasphere \
    libqcbassboost \
    libqcreverb \
    libqcvirt \
    libshoebox \
    vendor.qti.data.factory@2.0 \
    vendor.qti.data.factory@2.1 \
    vendor.qti.data.factory@2.2 \
    vendor.qti.data.mwqem@1.0 \
    vendor.qti.data.slm@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.0 \
    vendor.qti.hardware.bluetooth_sar@1.1 \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.qti.hardware.data.cne.internal.api@1.0 \
    vendor.qti.hardware.data.cne.internal.constants@1.0 \
    vendor.qti.hardware.data.cne.internal.server@1.0 \
    vendor.qti.hardware.data.connection@1.0 \
    vendor.qti.hardware.data.connection@1.1 \
    vendor.qti.hardware.data.dynamicdds@1.0 \
    vendor.qti.hardware.data.iwlan@1.0 \
    vendor.qti.hardware.data.latency@1.0 \
    vendor.qti.hardware.data.qmi@1.0 \
    vendor.qti.hardware.dsp@1.0 \
    vendor.qti.hardware.fingerprint@1.0 \
    vendor.qti.hardware.fm@1.0 \
    vendor.qti.hardware.mwqemadapter@1.0 \
    vendor.qti.hardware.qconfig@1.0 \
    vendor.qti.hardware.radio.am@1.0 \
    vendor.qti.hardware.radio.atcmdfwd@1.0 \
    vendor.qti.hardware.radio.ims@1.0 \
    vendor.qti.hardware.radio.ims@1.1 \
    vendor.qti.hardware.radio.ims@1.2 \
    vendor.qti.hardware.radio.ims@1.3 \
    vendor.qti.hardware.radio.ims@1.4 \
    vendor.qti.hardware.radio.ims@1.5 \
    vendor.qti.hardware.radio.ims@1.6 \
    vendor.qti.hardware.radio.internal.deviceinfo@1.0 \
    vendor.qti.hardware.radio.lpa@1.0 \
    vendor.qti.hardware.radio.lpa@1.1 \
    vendor.qti.hardware.radio.qcrilhook@1.0 \
    vendor.qti.hardware.radio.qtiradio@1.0 \
    vendor.qti.hardware.radio.qtiradio@2.0 \
    vendor.qti.hardware.radio.qtiradio@2.1 \
    vendor.qti.hardware.radio.qtiradio@2.2 \
    vendor.qti.hardware.radio.qtiradio@2.3 \
    vendor.qti.hardware.radio.qtiradio@2.4 \
    vendor.qti.hardware.radio.qtiradio@2.5 \
    vendor.qti.hardware.radio.uim@1.0 \
    vendor.qti.hardware.radio.uim@1.1 \
    vendor.qti.hardware.radio.uim@1.2 \
    vendor.qti.hardware.radio.uim_remote_client@1.0 \
    vendor.qti.hardware.radio.uim_remote_client@1.1 \
    vendor.qti.hardware.radio.uim_remote_client@1.2 \
    vendor.qti.hardware.radio.uim_remote_server@1.0 \
    vendor.qti.hardware.vpp@1.1 \
    vendor.qti.hardware.vpp@1.2 \
    vendor.qti.hardware.vpp@2.0 \
    vendor.qti.ims.rcsconfig@1.0 \
    vendor.qti.ims.rcsconfig@1.1 \
    vendor.qti.latency@2.0 \
    vendor.qti.voiceprint@1.0 \
    libadm \
    libadpcmdec \
    libdrc \
    libdsd2pcm \
    libfastcrc \
    libril \
    librilutils \
    libsmwrapper \
    libstreamparser \
    libsurround_3mic_proc \
    libvideoutils \
    com.arcsoft.node.supernightraw \
    libdepthmapwrapper_secure \
    libubifocus \
    com.qti.feature2.anchorsync \
    com.qti.feature2.arcrawpro \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.gs.cedros \
    com.qti.feature2.gs.kamorta \
    com.qti.feature2.gs.mannar \
    com.qti.feature2.gs.sdm865 \
    com.qti.feature2.gs.sm8350 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.settings.kamorta \
    com.qti.settings.mannar \
    com.qti.settings.sdm865 \
    com.qti.settings.sm8350 \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.qti.mcx.usecase.extension \
    com.qualcomm.qti.uceservice@2.0 \
    com.qualcomm.qti.uceservice@2.1 \
    com.qualcomm.qti.uceservice@2.2 \
    deviceInfoServiceModuleNr \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.gnss@2.1-impl-qti \
    vendor.qti.esepowermanager@1.1-impl \
    vendor.qti.gnss@4.0-impl \
    vendor.qti.hardware.alarm@1.0-impl \
    vendor.qti.hardware.eid@1.0-impl \
    vendor.qti.hardware.qseecom@1.0-impl \
    vendor.qti.hardware.qteeconnector@1.0-impl \
    vendor.qti.hardware.soter@1.0-impl \
    lib-imsSDP \
    lib-imscommon \
    lib-imsdpl \
    lib-imsqimf \
    lib-imsrcsservice \
    lib-imsservice \
    lib-imsvtcore \
    lib-imsxml \
    lib-rtpcommon \
    lib-rtpcore \
    lib-rtpsl \
    libGPQTEEC_vendor \
    libGPTEE_vendor \
    libGPreqcancel \
    libGPreqcancel_svc \
    libQSEEComAPI \
    libQTEEConnector_vendor \
    libQnnHtpAltPrepStub \
    libQnnHtpStub \
    libTouchInputVM \
    libTrustedInput \
    libTrustedInputTZ \
    libTrustedUI \
    libTrustedUITZ \
    libTrustedUIVM \
    libadsp_default_listener \
    libarcsoft_beautyshot \
    libarcsoft_face_detection \
    libarcsoft_face_tracking \
    libarcsoft_hdr \
    libarcsoft_nighthawk \
    libarcsoft_picselfie_algorithm \
    libarcsoft_piczoom \
    libarcsoft_qnnhtp \
    libarcsoft_rer \
    libarcsoft_super_night_raw \
    libasn1cper \
    libasn1crt \
    libasn1crtx \
    libbase64 \
    libcacertclient \
    libcdfw \
    libcdfw_remote_api \
    libcdsp_default_listener \
    libcpion \
    libcvpcpuRev_skel \
    libdataitems \
    libdisp-aba \
    libdisplayconfig.qti \
    libdisplayqos \
    libdisplayskuutils \
    libdpps \
    libdrmfs \
    libdrmtime \
    libdrmutils \
    libgarden \
    libgarden_haltests_e2e \
    libgdtap \
    libgeofencing \
    libgnss \
    libgnsspps \
    libhdcp1prov \
    libhdcp2p2prov \
    libhdcpsrm \
    libhdr_tm \
    libizat_client_api \
    libizat_core \
    libjnihelper \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    liblbs_core \
    libloadalgo_stub \
    libloc_api_v02 \
    libloc_socket \
    liblocation_api \
    liblocationservice \
    liblocationservice_glue \
    liblowi_client \
    liblowi_wifihal \
    libmctfengine_stub \
    libmdsprpc \
    libminkdescriptor \
    libminksocket \
    libmm-hdcpmgr \
    libnanopb \
    libnative-api \
    libnlnetmgr \
    liboemcrypto \
    libops \
    libpwirisIoctlWrapper \
    libpwirisPCS \
    libpwiriscalibrate \
    libpwirisfeature \
    libpwirishalwrapper \
    libpwirispq \
    libpwirisservice \
    libpwirissoft \
    libpwsoftirisPCS \
    libqcbor \
    libqcc_file_agent \
    libqcmaputils \
    libqdcm-mode-parser \
    libqisl \
    libqmiextservices \
    libqseed3 \
    libqtikeymaster4 \
    librcc \
    librcmask \
    librpmb \
    libsdedrm \
    libsdm-color \
    libsdm-colormgr-algo \
    libsdm-diag \
    libsdm-disp-vndapis \
    libsdmcore \
    libsdmextension \
    libsdmutils \
    libsdsprpc \
    libsecureui_svcsock \
    libsi \
    libslimclient \
    libsnapdragoncolor-manager \
    libsnapdragoncolor-pxlw \
    libsnapdragoncolor-qdcm \
    libsns_api \
    libsns_device_mode_stub \
    libsns_fastRPC_util \
    libsns_low_lat_stream_stub \
    libsns_registry_skel \
    libsnsdiaglog \
    libsoc_helper \
    libsoc_helper_jni \
    libspcom \
    libspl \
    libssc \
    libssc_default_listener \
    libssd \
    libsynergy_loc_api \
    libsysmon_cdsp_skel \
    libtinyxml2_1 \
    libtrustedapploader \
    libtzdrmgenprov \
    libvppclient \
    libvpphcp \
    libvpphvx \
    libvppimmotion \
    libvpplibrary \
    libvpptestutils \
    libwms \
    libwqe \
    libwvhidl \
    libxditk_DIT_Manager \
    libxditk_ISP \
    libxditk_ditBSP_JNI \
    libxtadapter \
    libxtwifi_server_protocol \
    libxtwifi_server_protocol_uri_v3 \
    libwvdrmengine \
    sensors.ssc \
    unnhal-acc-common \
    unnhal-acc-gpu \
    unnhal-acc-htp \
    vendor.display.color@1.0 \
    vendor.display.color@1.1 \
    vendor.display.color@1.2 \
    vendor.display.color@1.3 \
    vendor.display.color@1.4 \
    vendor.display.color@1.5 \
    vendor.display.postproc@1.0 \
    vendor.pixelworks.hardware.display@1.0 \
    vendor.pixelworks.hardware.display@1.1 \
    vendor.pixelworks.hardware.feature@1.0 \
    vendor.qti.diaghal@1.0_vendor \
    vendor.qti.esepowermanager@1.0 \
    vendor.qti.esepowermanager@1.1 \
    vendor.qti.gnss@1.0 \
    vendor.qti.gnss@1.1 \
    vendor.qti.gnss@1.2 \
    vendor.qti.gnss@2.0 \
    vendor.qti.gnss@2.1 \
    vendor.qti.gnss@3.0 \
    vendor.qti.gnss@4.0-service \
    vendor.qti.gnss@4.0 \
    vendor.qti.hardware.alarm@1.0 \
    vendor.qti.hardware.cacert@1.0 \
    vendor.qti.hardware.cvp@1.0 \
    vendor.qti.hardware.eid@1.0 \
    vendor.qti.hardware.factory@1.0 \
    vendor.qti.hardware.factory@1.1 \
    vendor.qti.hardware.qccsyshal@1.0 \
    vendor.qti.hardware.qdutils_disp@1.0 \
    vendor.qti.hardware.qseecom@1.0 \
    vendor.qti.hardware.qteeconnector@1.0 \
    vendor.qti.hardware.scve.objecttracker@1.0 \
    vendor.qti.hardware.scve.panorama@1.0 \
    vendor.qti.hardware.slmadapter@1.0 \
    vendor.qti.hardware.soter@1.0 \
    vendor.qti.hardware.trustedui@1.0 \
    vendor.qti.hardware.trustedui@1.1 \
    vendor.qti.hardware.tui_comm@1.0 \
    vendor.qti.hardware.vpp@1.3 \
    vendor.qti.ims.callcapability@1.0 \
    vendor.qti.ims.callinfo@1.0 \
    vendor.qti.ims.factory@1.0 \
    vendor.qti.ims.factory@1.1 \
    vendor.qti.ims.rcsconfig@2.0 \
    vendor.qti.ims.rcsconfig@2.1 \
    vendor.qti.imsrtpservice@3.0-service-Impl \
    vendor.qti.imsrtpservice@3.0_vendor \
    capi_v2_aptX_CLHDADV_Encoder \
    libQ6MSFR_manager_skel \
    libQnnHtpAltPrepSkel \
    libVppQnnHtp \
    libadsp_jpege_skel \
    libapps_mem_heap \
    libbitml_nsp_skel \
    libcamera_nn_skel \
    libcvpdsp_2_1 \
    libdspCV_skel \
    libdsp_streamer_binning \
    libfastcvadsp \
    libfastcvdsp_skel \
    libmctfengine_skel \
    libscveObjectSegmentation_skel \
    libscveT2T_skel \
    libsns_device_mode_skel \
    libsns_low_lat_stream_skel \
    libsuper_res_networks \
    libvpt_action_recognition \
    libmmosal \
    libmmparser_lite \
    com.qualcomm.qti.dpm.api@1.0 \
    lib-imsvideocodec \
    lib-imsvt \
    lib-imsvtextutils \
    lib-imsvtutils \
    libdiag_system \
    libdpmctmgr \
    libdpmfdmgr \
    libdpmframework \
    libdpmtcm \
    libimscamera_jni \
    libimsmedia_jni \
    vendor.qti.diaghal@1.0 \
    vendor.qti.imsrtpservice@3.0 \
    aptxals \
    CACertService \
    CneApp \
    IWlanService \
    QFingerprintService \
    TimeService \
    com.qualcomm.qti.gpudrivers.lahaina.api30 \
    PowerOffAlarm \
    HotwordEnrollmentOKGoogleHEXAGON \
    HotwordEnrollmentXGoogleHEXAGON \
    QtiTelephonyService \
    com.qualcomm.location \
    ims \
    qcrilmsgtunnel \
    tcmclient \
    com.android.hotwordenrollment.common.util \
    com.qti.dpmframework \
    com.qti.location.sdk \
    dpmapi \
    izat.xt.srv \
    qcrilhook \
    vendor.qti.hardware.alarm-V1.0-java \
    vendor.qti.hardware.fingerprint-V1.0-java \
    android.hardware.gnss@2.1-service-qti.xml \
    android.hardware.neuralnetworks@1.3-service-qti.xml \
    c2_manifest_vendor.xml \
    manifest_android.hardware.drm@1.3-service.widevine.xml \
    vendor.pixelworks.hardware.display.iris-service.xml \
    vendor.pixelworks.hardware.feature.irisfeature-service.xml \
    vendor.qti.diag.hal.service.xml \
    vendor.qti.gnss@4.0-service.xml \
    LightFingerprintPosition \
    adpl \
    adsprpcd \
    cdsprpcd \
    cnd \
    cnss-daemon \
    diag-router \
    dpmQmiMgr \
    dspservice \
    dualcam_default_cali.bin \
    firmware_version \
    garden_app \
    gaugeIC_status \
    hdcp1prov \
    hdcp2p2prov \
    hvdcp_opti \
    android.hardware.authsecret@1.0-service-qti \
    android.hardware.biometrics.fingerprint@2.1-service \
    android.hardware.bluetooth@1.0-service-qti \
    android.hardware.drm@1.3-service.widevine \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.gnss@2.1-service-qti \
    android.hardware.keymaster@4.0-service-qti \
    android.hardware.keymaster@4.0-strongbox-service-qti \
    android.hardware.keymaster@4.1-service-qti \
    android.hardware.neuralnetworks@1.3-service-qti \
    qconfigservice \
    qcrilNrd \
    vendor.display.color@1.0-service \
    vendor.pixelworks.hardware.display.iris-service \
    vendor.pixelworks.hardware.feature.irisfeature-service \
    vendor.qti.esepowermanager@1.1-service \
    vendor.qti.hardware.alarm@1.0-service \
    vendor.qti.hardware.capabilityconfigstore@1.0-service \
    vendor.qti.hardware.display.composer-service \
    vendor.qti.hardware.eid@1.0-service \
    vendor.qti.hardware.factory@1.0-service \
    vendor.qti.hardware.qseecom@1.0-service \
    vendor.qti.hardware.qteeconnector@1.0-service \
    vendor.qti.hardware.soter@1.0-service \
    vendor.qti.hardware.tui_comm@1.0-service-qti \
    vendor.qti.media.c2@1.0-service \
    ims_rtp_daemon \
    imsdaemon \
    init.asus.zram \
    init.kernel.post_boot-lahaina \
    init.kernel.post_boot \
    init.qcom.sensors \
    init.qti.chg_policy \
    init.qti.kernel \
    init.qti.media \
    init.qti.qcv \
    ipacm-diag \
    irisConfig \
    irisdbgc \
    irisdbgd \
    irsc_util \
    loadalgo \
    loc_launcher \
    lowi-server \
    lowirpcd \
    mlid \
    mmid \
    mutualex \
    netmgrd \
    nqnfcinfo \
    pd-mapper \
    pm-proxy \
    pm-service \
    port-bridge \
    power_off_alarm \
    ppd \
    qdcmss \
    qdss_qmi_helper \
    qfp-daemon \
    qmipriod \
    qrtr-cfg \
    qrtr-lookup \
    qrtr-ns \
    qseecomd \
    qti \
    qtigetprop \
    qtisetprop \
    read_battery_id_status \
    rmt_storage \
    sensors.qti \
    shsusrd \
    slim_daemon \
    sscrpcd \
    ssgqmigd \
    ssgtzd \
    tftp_server \
    thermal-engine \
    time_daemon \
    vendor.qti.hardware.soter@1.0-provision \
    vendor_modprobe \
    vmmgr \
    vppservice \
    xtra-daemon \
    dpmd

PRODUCT_PACKAGES += \
    vendor_lib64_rfsa_adsp_libsns_device_mode_skel_so \
    vendor_lib64_rfsa_adsp_libsns_low_lat_stream_skel_so
